---

- hosts: grid
  roles:
    - common
    - apache
    - mongodb
    - node
    - { role: grid, sudo_user: "{{ grid_user }}" }
    - { role: elasticsearch-mongo-river, tags: ["elasticsearch"] }
  vars_files:
    - secure.yml
  sudo: yes
