---

- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - python-pip
    - python-dev
    - supervisor
    - acl

- name: Install global python modules
  pip: name={{item}}
  sudo: True
  with_items:
    - virtualenv

- name: Create EIDR group
  user: name={{ eidr_group }}

- name: Create EIDR user
  user: name={{ eidr_user }} group={{ eidr_group }} shell=/bin/bash

- name: Create EIDR environment configuration
  template: src=config.j2 dest=/home/{{ eidr_user }}/grid_config group={{ eidr_group }} owner={{ eidr_user }}

# - name: Ensure EIDR is stopped
#   supervisorctl: name=eidr state=stopped
