---

  - name: Install meteor
    shell: curl https://install.meteor.com | /bin/sh chdir=/tmp creates=/usr/local/bin/meteor
    sudo: yes
    sudo_user: root
    
  - name: Create .ssh directory
    file: path=~/.ssh group={{ grid_group }} owner={{ grid_user }} state=directory
    
  - name: Create github key
    copy: content="{{git_key}}" dest=~/.ssh/id_rsa mode="0700"
    
  - name: Sync grid code
    git: 
      repo: git@github.com:ecohealthalliance/grid.git
      dest: "{{ grid_prefix }}"
      accept_hostkey: yes
      version: "{{ grid_git_version }}"
    register: grid
  
  - name: Remove untracked files
    shell: "git clean -f"
    args:
      chdir: "{{ grid_prefix }}"
    when: grid.changed

  - name: Create config
    template: src=meteor_config.j2 dest={{ grid_prefix }}/config mode=0755

  - name: Remove build directory
    file: path={{ grid_prefix }}/build state=absent
    when: grid.changed

  - name: meteor bundle
    command: meteor build build chdir={{ grid_prefix }}
    when: grid.changed

  - name: Unarchive bundle
    unarchive: src={{ grid_prefix }}/build/grid.tar.gz dest={{ grid_prefix }} copy=no
    when: grid.changed

  - name: Install supervisord config
    template: src=gridd.conf.j2 dest=/etc/supervisor/conf.d/gridd.conf
    sudo: yes
    sudo_user: root
    notify: reload supervisor
    with_items:
      - grid

  - name: Create import config
    tags: [import]
    template: src=import_config.j2 dest={{ grid_prefix }}/.scripts/config.py

  - name: Set up import python environment
    tags: [import]
    pip: requirements={{ grid_prefix }}/.scripts/requirements.txt virtualenv={{ grid_prefix }}/.scripts/env

  - name: Run import
    shell: "env/bin/python import_from_spreadsheets.py"
    tags: [import]
    args:
      chdir: "{{ grid_prefix }}/.scripts"

  - name: Restart grid process
    supervisorctl: name="grid" state=restarted
    when: grid.changed
    sudo: yes
    sudo_user: root
